import { useState, useCallback } from 'react';
import { v4 as uuidv4 } from 'uuid';
import { db } from '@/lib/db';
import { generateInfoCard } from '@/lib/api/client';
import type { InfoCard, ArtifactMetadata } from '@/types';

export type InfoCardStatus = 'idle' | 'generating' | 'complete' | 'error';

interface UseGenerateInfoCardOptions {
  onComplete?: (infoCard: InfoCard) => void;
  onError?: (error: string) => void;
}

export function useGenerateInfoCard(options: UseGenerateInfoCardOptions = {}) {
  const { onComplete, onError } = options;

  const [status, setStatus] = useState<InfoCardStatus>('idle');
  const [progress, setProgress] = useState(0);
  const [error, setError] = useState<string | null>(null);
  const [infoCard, setInfoCard] = useState<InfoCard | null>(null);

  const generate = useCallback(
    async (
      artifactId: string,
      imageBlob: Blob,
      metadata?: ArtifactMetadata
    ) => {
      // Reset state
      setStatus('generating');
      setProgress(0);
      setError(null);
      setInfoCard(null);

      try {
        // Convert blob to base64
        setProgress(20);
        const base64 = await blobToBase64(imageBlob);
        setProgress(40);

        // Call info card generation API
        const response = await generateInfoCard({
          imageBase64: base64,
          metadata: metadata ? {
            name: metadata.name,
            discoveryLocation: metadata.discoveryLocation,
            excavationLayer: metadata.excavationLayer,
            siteName: metadata.siteName,
            notes: metadata.notes,
            tags: metadata.tags,
          } : undefined,
        });

        setProgress(80);

        if (!response.success || !response.data?.infoCard) {
          throw new Error(response.error || response.data?.error || 'Info card generation failed');
        }

        const analysis = response.data.infoCard;

        // Create info card record
        const infoCardId = uuidv4();
        const now = new Date();
        const newInfoCard: InfoCard = {
          id: infoCardId,
          artifactId,
          createdAt: now,
          updatedAt: now,
          material: analysis.material || 'Unknown',
          estimatedAge: analysis.estimatedAge || {
            range: 'Unknown',
            confidence: 'low',
          },
          possibleUse: analysis.possibleUse || 'Unknown',
          culturalContext: analysis.culturalContext || 'Unknown',
          similarArtifacts: analysis.similarArtifacts || [],
          preservationNotes: analysis.preservationNotes || '',
          aiModel: analysis.aiModel || 'gemini-2.0-flash',
          aiConfidence: analysis.aiConfidence || 0,
          isHumanEdited: false,
          disclaimer: analysis.disclaimer || 'This analysis was generated by AI and should be verified by an expert.',
        };

        // Save to database
        await db.infoCards.add(newInfoCard);

        // Update artifact with info card ID
        await db.artifacts.update(artifactId, {
          infoCardId,
          status: 'complete',
          updatedAt: now,
        });

        setProgress(100);
        setInfoCard(newInfoCard);
        setStatus('complete');
        onComplete?.(newInfoCard);
      } catch (err) {
        const errorMessage = err instanceof Error ? err.message : 'Unknown error';
        setError(errorMessage);
        setStatus('error');
        onError?.(errorMessage);
      }
    },
    [onComplete, onError]
  );

  const reset = useCallback(() => {
    setStatus('idle');
    setProgress(0);
    setError(null);
    setInfoCard(null);
  }, []);

  return {
    generate,
    reset,
    status,
    progress,
    error,
    infoCard,
    isGenerating: status === 'generating',
  };
}

// Helper function
function blobToBase64(blob: Blob): Promise<string> {
  return new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.onloadend = () => {
      const result = reader.result as string;
      const base64 = result.split(',')[1];
      resolve(base64);
    };
    reader.onerror = reject;
    reader.readAsDataURL(blob);
  });
}
